name: Deploy to Nuget

on:
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: "./src/AllSeer.Cli"
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  publish:
    if: ${{ false }}  # disable for now

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore packages
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: Get Version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack Nuget Package
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }}

      - name: Push package to Nuget
        run: |
          dotnet nuget push ${{ env.PROJECT_PATH }}/**/*.nupkg -k ${{ secrets.NUGET_DEPLOY_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --no-symbols true
